In [14]:
from numpy import exp, array, random, dot

class NeuralNetwork():
    def __init__(self):
        # Seed the random number generator, so it generates the same numbers
        # every time the program runs.
        random.seed(1)

        # We model a single neuron, with 3 input connections and 1 output connection.
        # We assign random weights to a 3 x 1 matrix, with values in the range -1 to 1
        # and mean 0.
        self.synaptic_weights = 2 * random.random((3, 1)) - 1

    # The Sigmoid function, which describes an S shaped curve.
    # We pass the weighted sum of the inputs through this function to
    # normalise them between 0 and 1.
    def __sigmoid(self, x):
        return 1 / (1 + exp(-x))

    # The derivative of the Sigmoid function.
    # This is the gradient of the Sigmoid curve.
    # It indicates how confident we are about the existing weight.
    def __sigmoid_derivative(self, x):
        return x * (1 - x)

    # We train the neural network through a process of trial and error.
    # Adjusting the synaptic weights each time.
    def train(self, training_set_inputs, training_set_outputs, number_of_training_iterations):
        for iteration in range(number_of_training_iterations):
            # Pass the training set through our neural network (a single neuron).
            output = self.think(training_set_inputs)

            # Calculate the error (The difference between the desired output
            # and the predicted output).
            error = training_set_outputs - output

            # Multiply the error by the input and again by the gradient of the Sigmoid curve.
            # This means less confident weights are adjusted more.
            # This means inputs, which are zero, do not cause changes to the weights.
            adjustment = dot(training_set_inputs.T, error * self.__sigmoid_derivative(output))

            # Adjust the weights.
            self.synaptic_weights += adjustment

    # The neural network thinks.
    def think(self, inputs):
        # Pass inputs through our neural network (our single neuron).
        return self.__sigmoid(dot(inputs, self.synaptic_weights))


if __name__ == "__main__":
    
    neural_network= NeuralNetwork()
    
    print("Random starting synaptic weights: ")
    print(neural_network.synaptic_weights)

    # The training set. We have 4 examples, each consisting of 3 input values
    # and 1 output value.
    training_set_inputs = array([[0, 0, 1], [1, 1, 1], [1, 0, 1], [0, 1, 1]])
    training_set_outputs = array([[0, 1, 1, 0]]).T

    
    # Train the neural network using a training set.
    # Do it 10,000 times and make small adjustments each time.
    neural_network.train(training_set_inputs, training_set_outputs, 10000)

    print("\nNew synaptic weights after training: ")
    print(neural_network.synaptic_weights)

    
    
    # Test the neural network with a new situation.
    print("\nConsidering new situation [1, 0, 0] -> ?: ")
    print(neural_network.think(array([1, 0, 0])))

Random starting synaptic weights: 
[[-0.16595599]
 [ 0.44064899]
 [-0.99977125]]

New synaptic weights after training: 
[[ 9.67299303]
 [-0.2078435 ]
 [-4.62963669]]

Considering new situation [1, 0, 0] -> ?: 
[0.99993704]


In [5]:
from tensorflow import keras
# from keras.models import Sequential
# from keras.layers import Dense

import numpy as np

np.random.seed(7)
dataset=np.loadtxt("pima-indians-diabetes.csv",delimiter=',')

#spliting into input X and output Y
X=dataset[:,0:8] # 8 input vars
Y=dataset[:,8] # 1 output var
dataset

array([[  6.   , 148.   ,  72.   , ...,   0.627,  50.   ,   1.   ],
       [  1.   ,  85.   ,  66.   , ...,   0.351,  31.   ,   0.   ],
       [  8.   , 183.   ,  64.   , ...,   0.672,  32.   ,   1.   ],
       ...,
       [  5.   , 121.   ,  72.   , ...,   0.245,  30.   ,   0.   ],
       [  1.   , 126.   ,  60.   , ...,   0.349,  47.   ,   1.   ],
       [  1.   ,  93.   ,  70.   , ...,   0.315,  23.   ,   0.   ]])

In [17]:

import numpy as np
import random
import os

a=1 #learning rate

bias=1 #value of bias

weights = [random.random(),random.random(),random.random()]
# 3 weights consist 2 neuron and 1 bias
  
def perceptron(input1,input2,output):
    outputP= input1*weights[0] + input2*weights[1]+bias*weights[2]
    if outputP > 0:
        outputP = 1
    else:
        outputP = 0
    error= output - outputP
    weights[0] += error * input1 * a
    weights[1] += error * input2 * a
    weights[2] += error * bias * a

for i in range(50): 
    perceptron(1,1,1)#T or T
    perceptron(1,0,1)#T or F
    perceptron(0,1,1)#F or T
    perceptron(0,0,0)#F or F
    
# training the model for given 3rd argument of perceptron    
x=int(input())
y= int(input())
outputP = x*weights[0] + y*weights[1] + bias*weights[2]
print(weights)
if outputP > 0:
    outputP=1
else:
    outputP=0
print(x,"or",y,"is :",outputP)

outputP = 1/(1+np.exp(-outputP)) #activation function

1
0
[1.5132220645030405, 0.7413611494732402, -0.5840508473019806]
1 or 0 is : 1


# pima-indians dataset sequential model

In [24]:
from tensorflow import keras
from tensorflow.keras import models
from tensorflow.keras.layers import Dense
from tensorflow.keras import Sequential
import numpy as np
np.random.seed(7)
dataset= np.loadtxt("pima-indians-diabetes.csv",delimiter=",")
#spliting into 8 input and 1 output
X=dataset[:,0:8]
Y=dataset[:,8]
dataset

array([[  6.   , 148.   ,  72.   , ...,   0.627,  50.   ,   1.   ],
       [  1.   ,  85.   ,  66.   , ...,   0.351,  31.   ,   0.   ],
       [  8.   , 183.   ,  64.   , ...,   0.672,  32.   ,   1.   ],
       ...,
       [  5.   , 121.   ,  72.   , ...,   0.245,  30.   ,   0.   ],
       [  1.   , 126.   ,  60.   , ...,   0.349,  47.   ,   1.   ],
       [  1.   ,  93.   ,  70.   , ...,   0.315,  23.   ,   0.   ]])

In [26]:
#create model
model=Sequential()
model.add(Dense(12,input_dim=8,activation='relu'))
model.add(Dense(8,activation='relu'))
model.add(Dense(1,activation='sigmoid'))


In [28]:
model.compile(optimizer='adam',loss='binary_crossentropy', metrics=['accuracy'])


In [31]:
model.fit(X,Y,epochs=150,batch_size=10)

Epoch 1/150
768/768 [==============================] - 0s 401us/sample - loss: 0.5455 - acc: 0.7266
Epoch 2/150
768/768 [==============================] - 0s 343us/sample - loss: 0.5011 - acc: 0.7643
Epoch 3/150
768/768 [==============================] - 0s 377us/sample - loss: 0.5127 - acc: 0.7552
Epoch 4/150
768/768 [==============================] - 0s 414us/sample - loss: 0.5143 - acc: 0.7461
Epoch 5/150
768/768 [==============================] - 0s 473us/sample - loss: 0.4899 - acc: 0.7708
Epoch 6/150
768/768 [==============================] - 0s 303us/sample - loss: 0.4935 - acc: 0.7656
Epoch 7/150
768/768 [==============================] - 0s 491us/sample - loss: 0.5029 - acc: 0.7669
Epoch 8/150
768/768 [==============================] - 0s 419us/sample - loss: 0.4921 - acc: 0.7669
Epoch 9/150
768/768 [==============================] - 0s 253us/sample - loss: 0.4899 - acc: 0.7656
Epoch 10/150
768/768 [==============================] - 0s 291us/sample - loss: 0.4835 - acc: 0.7591

In [38]:
scores= model.evaluate(X,Y)
print("\n%s: %.2f%%" %(model.metrics_names[1],scores[1]*100))

768/768 [==============================] - 0s 108us/sample - loss: 0.4579 - acc: 0.7721

acc: 77.21%


In [44]:
scores
# model.metrics_names


[0.45788536220788956, 0.77213544]

In [63]:
scr= model.evaluate(X,Y)
print("Accuracy:",scr[1]*100)

768/768 [==============================] - 0s 36us/sample - loss: 0.4513 - acc: 0.8008
Accuracy: 80.078125
